apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.mlflow.fullname }}
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
